project:
  type: website

website:
  title: "RNAseq qc exercises"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd


format: 
  html:
    code-fold: true
    code-summary: "Click here to show the code"
    code-tools: true
    theme: united
    self-contained: true
    page-layout: full
    toc: true
    css: styles.css
# engine: knitr



